name: Tic-Taction-Toe
on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  play:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tic Taction Toe
        uses: AnsellMaximilian/tic-taction-toe@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
